[project]
name = "metatomic-torch"
dynamic = ["version", "authors", "dependencies"]
requires-python = ">=3.10"

readme = "README.rst"
license = "BSD-3-Clause"
description = "Interface between atomistic machine learning models and simulation tools"

keywords = ["machine learning", "molecular modeling", "torch"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
homepage = "https://docs.metatensor.org/metatomic/"
documentation = "https://docs.metatensor.org/metatomic/"
repository = "https://github.com/metatensor/metatomic"
changelog = "https://docs.metatensor.org/metatomic/latest/torch/CHANGELOG.html"

### ======================================================================== ###
[build-system]
requires = [
    "setuptools >=77",
    "packaging >=26",
    "cmake",
    "metatensor-torch",
    # we also add torch to this list in the build backend below
]

# we use a custom build backend to add torch only when building the wheel
# and not the sdist; as well as to control which version of torch we built against
build-backend = "backend"
backend-path = ["build-backend"]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["metatomic*"]
namespaces = true

### ======================================================================== ###
[tool.pytest.ini_options]
python_files = ["*.py"]
testpaths = ["tests"]
filterwarnings = [
    "error",
    # TorchScript deprecation warnings
    "ignore:`torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`:DeprecationWarning",
    "ignore:`torch.jit.save` is deprecated. Please switch to `torch.export`:DeprecationWarning",
    "ignore:`torch.jit.load` is deprecated. Please switch to `torch.export`:DeprecationWarning",
    "ignore:`torch.jit.script` is not supported in Python 3.14+:DeprecationWarning",
    "ignore:`torch.jit.save` is not supported in Python 3.14+:DeprecationWarning",
    "ignore:`torch.jit.load` is not supported in Python 3.14+:DeprecationWarning",
    # There is a circular dependency between metatomic-torch and vesin.metatomic
    "ignore:.*vesin.metatomic was only tested with metatomic.torch >=0.1.3,<0.2.*:UserWarning",
    # deprecation warning from vesin
    "ignore:`compute_requested_neighbors_from_options` is deprecated and will be removed in a future version:UserWarning",
]
